[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#16161a"
secondaryBackgroundColor = "#1e1e24"
textColor = "#f2f2ef"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
